# Copyright 2012 - XemsDoom/Phiwa DragonTravel Licence GPLv3
#
# - Do NOT use tabs in this config file.
# - Read the comment carefully when altering values.
# - Have fun. 

# Do not touch this option at all(!), it's a check if you are running the recent configuration version
ConfigVersion: 1.5

# ----->SPOUT FEATURES<------
# Music to play when somebody starts a travel
# Enter the URL which goes DIRECTLY to the file
# Use ogg/wav/mp3 files for playing, otherwhise you get errors!
# The default track is made by me(Xems) and can be used for whatever you like
# IT IS SUGGESTED TO INSERT AN OWN LINK HERE!
MusicURL: 'http://dl.dropbox.com/u/37237580/DragonTravelDemo.ogg'
MessageOnPlay: true

#Key for opening the GUI, please notice that this is only available for SpoutCraft users!
#A key is for example: "KEY_O" or "KEY_U"
GUIopenKey: 'KEY_L'

# ------>ECONOMY STUFF<------
# Set Economy to "true" to enable withdraws on travels
# You must have >Vault< installed for using this feature!
Economy: false

# This costs you define here are for when a player executes commands.
# If you use signs, the cost on the sign will be withdraw
# Choose the amount of money a normal travel costs
PayTravel: 5.0
# Choose the amount of money a flight costs
PayFlight: 5.0
# Choose the amount of money a choordinates-travel costs
PayCoords: 10.0
# Choose the amount of money a home-travel costs
PayHome: 0.0
# Choose the amount of money a homeset costs
HomeSetCost: 0.0
# Choose the amount of money a player-travel costs
PaytoPlayer: 7.0

# ------->TRAVEL COMMONS<-------

# Choose how high the dragon flys during a travel(not flight)
# The number represents blocks
# Numbers over sky height are allowed
TravelHeight: 100

# If enabled, players can only mount and travel from stations
UseStation: false
# Should markers on station/destination creations be placed?
UseStatDestMarker: true
# Set the radius of a station
# The number represents blocks
DistancetoStation: 5.0
# Set to true if you want players only be able
# to use signs for destination-travelling
# This option disables the command /dt travel
UseOnlySigns: false

# If set to true, DragonTravel will try to ignore
# protections on areas which try to prevent it from
# spawning a dragon.
IgnoreAntiMobspawnAreas: true

# Choose which dragon-entites can't destroy blocks
AntiGriefallDragons: false
AntiGriefDragonTravelDragons: true

# Set the dragon's fly speed
# The number represents the blocks in 1 server tick, 20 ticks = 1 second
# Do not set it over 1.0!
DragonSpeed: 0.5

# Choose the commands which can't be executed while being on a dragon
# Make sure to list all commands which could teleport a player away from the dragon!
# You must only define the first word with the "/", in this list!
CommandPrevent:
- /spawn
- /f
- /kill
- /home

# The Random Destination
# You can set borders beyond which there will be no random destination created.
RandomDest-Name: '_random_'
X-Axis:
    MinX: -100
    MaxX: 100
Z-Axis:
    MinZ: -100
    MaxZ: 100

#Legit old Dragon:
#
#                                            (
#                                              )
#
#
#                                            (      )
#                                             ) )  ( (
#  __..--...___                                (    \ )
#''            ``---..__               .--._    )    ),
#            .      ,  -``,..__       /.   _`=_     ((
#          ,                .  `--.._(    (e)`a)     )
#                 '    ,'  ,    ---._ `-..-'   \_.  (
#         ,      |    ,'   ::   ,--._ ,        > (__
#    ,          |'    |.   `\. /     |   ___  ' >  /
#        '      |:    |:.    `:      `.__._ `-.  O `)
#   |    |      |: -  \::. .-'             `-. `.  /
#   |    /\     ::.    '\:'                   `\_\/
#   |    |:.    `::...-'--
#   :    \::\     `:' ________________________________________________
#   :     \:;;.._,.8a.
#   ::      `8Pa88888888888aa.
#_  ::: _..a8888888888888888888a.
#888aaa8888888888888888888888888888a.
#888888888888888888888888888888888888888888a.
#      ""Y8888888888888P""'   `"88888888888888a.
#                                 `88888888888888
#                                     `8888888888
#                                       `8888888'