name: DragonTravel
main: com.xemsdoom.dt.DragonTravelMain
author: XemsDoom & Phiwa & ellbristow
version: 1.8.3b
softdepend: [Vault, SpoutPlugin, AntiCheat]
permissions:
    dt.mod.flight:
        default: op
        description: Advanced permissions for creating removing flights
        children:
            dt.saveflight: true
            dt.createflight: true
            dt.flightsigns: true
            dt.remflight: true
            dt.setwp: true
            dt.remwp: true
            dt.mod.travel: true
    dt.mod.travel:
        default: op
        description: Advanced permissions for creating removing travels
        children:
            dt.setdest: true
            dt.setstat: true
            dt.travelsigns: true
            dt.remdest: true
            dt.remstat: true
            dt.userplus: true
    dt.userplus:
        default: op
        description: Basic permissions and some advanced features
        children:
            dt.ctravel: true
            dt.ptravel: true
            dt.mount: true
            dt.user: true
    dt.user:
        default: op
        description: Basic permissions
        children:
            dt.stopmusic: true
            dt.destlist: true
            dt.dismount: true
            dt.statlist: true
            dt.travel: true
            dt.travelsigns.use: true
            dt.home.set: true
            dt.home: true
            dt.ptoggle: true
            dt.flight: true
            dt.flightsigns.use: true
            dt.flightlist: true
    dt.nocost:
        default: op
        description: No withdraws
    dt.gui:
        default: op
        description: Opening the GUI
    dt.statdragon:
        default: op
        description: Creating stationary dragons
    dt.remdragons:
        default: op
        description: Removing ghost dragons
    dt.saveflight:
        default: op
        description: Saving flights
    dt.createflight:
        default: op
        description: Creating flights
    dt.flightsigns:
        default: op
        description: Creating flightsigns
    dt.remflight:
        default: op
        description: Removing flight
    dt.setwp:
        default: op
        description: Setting waypoints
    dt.remwp:
        default: op
        description: Removing waypoints
    dt.setdest:
        default: op
        description: Setting destinations
    dt.setstat:
        default: op
        description: Setting stations
    dt.travelsigns:
        default: op
        description: Creating travelsigns
    dt.remdest:
        default: op
        description: Removing destinations
    dt.remstat:
        default: op
        description: Removing stations
    dt.ctravel:
        default: op
        description: Coords travel
    dt.ptravel:
        default: op
        description: Player travel
    dt.mount:
        default: op
        description: Mounting a dragon
    dt.stopmusic:
        default: op
        description: Stoppping the music
    dt.destlist:
        default: op
        description: Destination list
    dt.statlist:
        default: op
        description: Station list
    dt.travel:
        default: op
        description: Normal travel
    dt.travelsigns.use:
        default: op
        description: Using travel signs
    dt.home.set:
        default: op
        description: Setting home
    dt.home:
        default: op
        description: Home travel
    dt.ptoggle:
        default: op
        description: Accepting unaccepting player travel
    dt.flight:
        default: op
        description: Flight
    dt.flightsigns:
        default: op
        description: Using flight signs
    dt.flightlist:
        default: op
        description: Creating travelsigns
    dt.dismount:
        default: op
        description: Dismounting the dragon
commands:
    dt:
        usage: